export const motivationalPhrases = [
  "A liberdade é a posse suprema daqueles que têm coragem de conquistá-la.",
  "O sucesso é a soma de pequenos esforços repetidos dia após dia.",
  "Riqueza é a liberdade de dispor do seu próprio tempo e propósito.",
  "Não espere por circunstâncias ideais; crie o seu próprio destino.",
  "Onde o foco reside, a energia flui e a prosperidade floresce.",
  "Sua vida não melhora por acaso, melhora por meio da mudança consciente.",
  "O propósito da vida é viver uma vida com propósito e abundância.",
  "Tudo posso naquele que me fortalece.",
  "A bênção do Senhor traz riqueza e não inclui dor alguma.",
  "Conhecereis a verdade, e a verdade vos libertará.",
  "Onde não há visão, o povo perece.",
  "Consagre seus planos ao Senhor e eles serão bem-sucedidos.",
  "Peça e lhe será dado; busque e encontrará; bata e a porta se abrirá.",
  "Para tudo há um tempo, e um propósito para cada etapa debaixo do céu.",
  "Deus nos deu espírito de poder, de amor e de equilíbrio.",
  "A sabedoria é melhor que o ouro, e o entendimento melhor que a prata.",
  "O homem faz planos, mas a resposta certa vem do Senhor.",
  "Seja forte e corajoso; não desanime, pois o Senhor está com você.",
  "Grandes coisas estão por vir para aqueles que acreditam e trabalham.",
  "A mente que se abre a uma nova ideia jamais retornará ao seu tamanho original.",
  "O único lugar onde o sucesso vem antes do trabalho é no dicionário.",
  "A disciplina é a ponte entre metas e realizações.",
  "O que não nos mata, nos torna mais fortes.",
  "Se você quer ir rápido, vá sozinho. Se quer ir longe, vá acompanhado.",
  "A melhor maneira de prever o futuro é criá-lo.",
  "Não é a carga que o derruba, mas a maneira como você a carrega.",
  "Vença a si mesmo e terá vencido o mundo.",
  "A oportunidade favorece apenas a mente preparada.",
  "O sucesso não consiste em nunca errar, mas em nunca desistir.",
  "O risco mais perigoso de todos é o risco de passar a vida sem fazer o que quer.",
  "Mude seus pensamentos e você mudará seu mundo.",
  "O que você faz hoje pode melhorar todos os seus amanhãs.",
  "A excelência não é um ato, mas um hábito.",
  "Sua única limitação é aquela que você impõe em sua própria mente.",
  "O fracasso é apenas a oportunidade de recomeçar com mais inteligência.",
  "O segredo do sucesso é a constância do propósito.",
  "Quem tem um 'porquê' enfrenta qualquer 'como'.",
  "A vida começa onde termina sua zona de conforto.",
  "Não conte os dias, faça os dias contarem.",
  "A felicidade não é algo pronto. Ela vem de suas próprias ações.",
  "A persistência é o caminho do êxito.",
  "O entusiasmo é a maior força da alma.",
  "Sempre parece impossível até que seja feito.",
  "A jornada de mil milhas começa com um único passo.",
  "O que você busca também está buscando você.",
  "Acredite que você pode e você já está no meio do caminho.",
  "Tudo o que a mente humana pode conceber e acreditar, ela pode realizar.",
  "O sucesso é caminhar de fracasso em fracasso sem perder o entusiasmo.",
  "A única pessoa que você está destinado a se tornar é a pessoa que você decide ser.",
  "A vida é 10% o que acontece comigo e 90% como eu reajo a isso.",
  "A maior glória não reside em nunca cair, mas em levantar-se cada vez que caímos.",
  "Seus sonhos não têm data de validade. Respire fundo e tente novamente.",
  "O tempo é o único recurso que você não pode recuperar.",
  "Seja a mudança que você deseja ver no mundo.",
  "A paciência é amarga, mas seu fruto é doce.",
  "A imaginação é mais importante que o conhecimento.",
  "O gênio é 1% inspiração e 99% transpiração.",
  "Não tente ser um homem de sucesso, mas sim um homem de valor.",
  "A simplicidade é o último grau de sofisticação.",
  "O saber a gente aprende com os mestres. A sabedoria, com a vida.",
  "O universo conspira a favor de quem não desiste.",
  "A coragem não é a ausência do medo, mas o domínio sobre ele.",
  "Foque na solução, não no problema.",
  "O que você foca, expande.",
  "Pense grande, comece pequeno, aprenda rápido.",
  "A gratidão é a memória do coração.",
  "O silêncio é a moldura da sabedoria.",
  "A sorte é o que acontece quando a preparação encontra a oportunidade.",
  "O homem que remove montanhas começa carregando pedras pequenas.",
  "A maior riqueza é a saúde da mente e do corpo.",
  "Seja dono do seu silêncio para não ser escravo das suas palavras.",
  "A vida é curta demais para viver o sonho de outra pessoa.",
  "O valor de uma ideia reside no seu uso.",
  "Para ganhar o que ninguém ganha, você deve fazer o que ninguém faz.",
  "Seja humilde para aprender e resiliente para vencer.",
  "O amanhã pertence àqueles que se preparam hoje.",
  "Trabalhe enquanto eles dormem, estude enquanto eles se divertem.",
  "A vitória pertence aos mais perseverantes.",
  "Não diminua seus sonhos, aumente sua habilidade.",
  "Se você pode sonhar, você pode fazer.",
  "A direção é mais importante que a velocidade.",
  "Seja grato pelo que tem enquanto busca o que deseja.",
  "O primeiro passo para o sucesso é acreditar que ele é possível.",
  "Transforme seus obstáculos em degraus para sua subida.",
  "A maior lição da vida é que nada é impossível.",
  "A abundância flui para quem vive em estado de gratidão.",
  "Sua vibração atrai sua tribo e seu destino.",
  "O conhecimento é poder, mas a ação é o que gera resultados.",
  "Nunca é tarde demais para ser o que você poderia ter sido.",
  "O sucesso não é para os sortudos, é para os obstinados.",
  "Faça o melhor que puder, onde você estiver, com o que você tiver.",
  "A vontade de vencer é importante, mas a vontade de se preparar é vital.",
  "Não pare até se orgulhar de si mesmo.",
  "Grandes mentes discutem ideias; mentes médias discutem eventos.",
  "O esforço só é plenamente recompensado quando a pessoa se recusa a desistir.",
  "Nada é permanente, exceto a mudança.",
  "A melhor vingança é um sucesso estrondoso.",
  "Acredite nos seus instintos; eles raramente falham.",
  "O que você faz em segredo determina seu sucesso em público.",
  "A vida retribui quem trabalha com integridade e paixão."
];
